### ISSUE TITLE
Unexpected keyword argument error when enabling notifications

### ISSUE THREAD

**Issue by harshshah88** [getsenic/gatt-python#27]
I am getting the following error in characteristic_enable_notifications_succeeded():

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/local/lib/python3.5/dist-packages/gatt/gatt_linux.py", line 618, in _enable_notifications_succeeded
    self.service.device.characteristic_enable_notifications_succeeded(characteristic=self)
TypeError: characteristic_enable_notifications_succeeded() got an unexpected keyword argument 'characteristic'`

I am not sure what is causing this issue.

**Comment by larsblumberg** [comment]
Which BlueZ version are you using? Did you try a system restart?

**Comment by harshshah88** [comment]
I am using BlueZ version 5.48 and have tried restarting the system but had no luck with that.
