### ISSUE TITLE
BlueZ work SDK not

### ISSUE THREAD

**Issue by PepCa1979** [getsenic/gatt-python#37]
hi installation from package so far so good bluez5.9 works fine (I hope), gatt and dbus for python seems ok, but sudo gattctl --discover crash:

pi@raspberrypi:~/bluez-5.9 $ sudo gattctl --discover
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gatt/gatt_linux.py", line 138, in start_discovery
    self._adapter.SetDiscoveryFilter(discovery_filter)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "SetDiscoveryFilter" with signature "a{ss}" on interface "org.bluez.Adapter1" doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gattctl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/gattctl.py", line 116, in main
    device_manager.start_discovery()
  File "/usr/local/lib/python3.5/dist-packages/gatt/gatt_linux.py", line 149, in start_discovery
    raise _error_from_dbus_error(e)
gatt.errors.Failed: Method "SetDiscoveryFilter" with signature "a{ss}" on interface "org.bluez.Adapter1" doesn't exist

Where could be a problem, what am I doing wrong?

**Comment by PepCa1979** [comment]
RPI3 (latest rapsbian) btw

**Comment by larsblumberg** [comment]
If you are really using BlueZ version 5.9, you should definitely update to at least BlueZ 5.43, as per the docs of the `gatt-python` library.
